--- #YAML:1.0
name:               Mojo-Autotask
version:            0.01
abstract:           Interface to the Autotask WebServices SOAP API and ExecuteCommand URL builder
author:
    - Stefan Adams <stefan@adams.fm>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::SSLeay:     0
    Devel::Size:       0
    Encode:            0
    File::Find::Rule:  0
    Memory::Usage:     0
    MIME::Base64:      0
    MIME::Lite:        0
    Mojolicious:       0
    SOAP::Lite:        0
    Test::Class:       0
    Test::MockObject:  0
    XML::LibXML:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4